---


- name: "[CEPH-POC][CONFIG-BASIC] Install Satellite CA"
  shell: "/usr/bin/yum localinstall -e 0 -y {{ satellite_ca }}"
  when: "'{{ resource }}' == 'satellite'"

- name: "[CEPH-POC][CONFIG-BASIC] Register to Satellite"
  redhat_subscription:
    state: present
    activationkey: "{{ satellite_ak }}"
    org_id: "{{ satellite_org }}"
  when: "'{{ resource }}' == 'satellite'"

  #- name: "[CEPH-POC] Register to the CDN"
  #  redhat_subscription:
  #    state: present
  #    username: "{{ cdn_user }}"
  #    password: "{{ cdn_password }}"
  #    pool_ids: "{{ cdn_pool }}"
  #  when: "'{{ resource }}' == 'cdn'"
#Module not available in ansible 2.4
#- name: "[CEPH-POC][CONFIG-BASIC] Enable a RHSM repository"
#  rhsm_repository:
#    name: "{{ item }}"
#  with_items:
#    - rhel-7-server-rpms
#    - rhel-7-server-extras-rpms
#    - rhel-7-server-rhceph-3-tools-rpms
#    - rhel-7-server-rh-common-rpms

- name: "[CEPH-POC][CONFIG-BASIC] Enable a RHSM repository"
  command: "subscription-manager repos --enable {{ item }}"
  with_items:
    - rhel-7-server-rpms
    - rhel-7-server-extras-rpms
    - rhel-7-server-rh-common-rpms

