---

- name: "[VM_CONFIG] Clear OLD nameserver from /etc/resolv.conf"
  lineinfile:
    path: /etc/resolv.conf
    regexp: "^nameserver"
    state: absent

- name: "[VM_CONFIG] Set unique nameserver in /etc/resolv.conf"
  lineinfile:
    path: /etc/resolv.conf
    regexp: "^nameserver"
    line: "nameserver {{ vm_dns }}"
    state: present

- name: "[VM_CONFIG] Set Hostname {{ vm_name }}"
  hostname:
     name: "{{ vm_name }}"

- name: "[VM_CONFIG] Stop the cloud-init service"
  systemd:
    name: cloud-init
    state: stopped
    enabled: no

#- name: "[VM_CONFIG] Clean old subscription-manager data"
#  shell: /usr/bin/subscription-manager clean
#
#- name: "[VM_CONFIG] Install Satellite CA"
#  shell: "/usr/bin/yum localinstall -e 0 -y {{ satellite_ca }}"
#
#- name: "[VM_CONFIG] Register to the CDN"
#  redhat_subscription:
#    state: present
#    username: "{{ cdn_user }}"
#    password: "{{ cdn_password }}"
#    pool_ids: "{{ cdn_pool }}"
#  when: "'{{ subs_mode }}' == 'cdn'"
#
#- name: "[VM_CONFIG] Register to Satellite"
#  redhat_subscription:
#    state: present
#    activationkey: "{{ satellite_ak }}"
#    org_id: "{{ satellite_org }}"
#    force_register: yes
#  when: "'{{ subs_mode }}' == 'satellite'"
#
#- name: "[VM_CONFIG] Enable a RHSM repository"
#  rhsm_repository:
#    name: "{{ item }}"
#  with_items:
#    - rhel-7-server-rpms
#    - rhel-7-server-extras-rpms
#    - rhel-7-server-rh-common-rpms
#
#- name: "[VM_CONFIG] Install the repositories"
#  yum:
#    update_cache: yes
#    name: ovirt-guest-agent-common
#    state: latest
#
#- name: "[VM_CONFIG] Enable ovirt-guest-tools service"
#  systemd:
#    state: started
#    name: ovirt-guest-agent.service
#
#- name: "[CEPH-POC][CONFIG-BASIC] Stop the cloud-init service"
#  systemd:
#    name: cloud-init
#    state: stopped
#    enabled: no
